n = str(input('Qual seu nome: ')).strip()
nome = n.split()
print('Prazer em te conhecer! {}'.format(nome[0]))
print('Seu nome completo é: {}'.format(n))
print('Seu primeiro nome é: {}'.format(nome[0]))
print('Seu ultimo nome é: {}'.format(nome[len(nome)-1]))